### ISSUE TITLE
Add the ability to supply helpers to a specific render call?

### ISSUE THREAD

**Issue by mxriverlynn** [rotundasoftware/underscore-template-helpers#1]
Hi David!

I saw your comment on my blog post, and I really like what I see with the direction of this add-on. I'm wondering if you would be interested in adding the ability to supply template helper functions through an individual call to the `template()` function instead of as global functions?

To get straight to the pont - I would love to be able to remove the code that I have in MarionetteJS, for handling template helpers, in favor of this plugin. 

My thought was that the third parameter for `template` could be augmented to supply a `templateHelpers` key:

``` js
var html = _.template(template, data, {
  templateHelpers: {
    // ...
  }
});
```

I've never been super happy with the way I'm passing the functions through the data parameter in Marionette. Augmenting the third parameter like this would make more sense and solve some potential problems that my code has.

**Comment by dgbeck** [comment]
Hi Derick,

I am certainly honored that you like the contribution! You have done an awesome job on marionette.

If I am understanding correctly, you are suggesting a mixin that replaces the built in underscore function with one that has separate parameters for data and helper functions. The helper functions you pass in through the third param, instead of being globally accessible from any template as in the current mixin, would be local to the specific template function that is returned. So the new _.template function would effectively be the same as the underscore's original _.template function but would have an extra parameter so you could cleanly separate data from helper functions.

You would then be able to get away from the "mixinTemplateHelpers" stuff and pass the helpers given by the "templateHelpers" attribute directly to the modified underscore _.template function.

Is this correct?

David

**Comment by dgbeck** [comment]
Or maybe you are envisioning the mixin as it is, with support for global helpers, just adding support for that third parameter?

**Comment by dgbeck** [comment]
Closing this. See discussion on #2 - not sure how useful this would be. If you have additional thoughts Derick let me know.
